<?php

namespace Drupal\zipcode_finder\Plugin\Field\FieldType;

use Drupal\Core\Field\Annotation\FieldType;
use Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem;
use Drupal\zipcode_finder\Entity\ZipcodeFinder;

/**
 * @FieldType(
 *     id = "zipcode_finder_computed_item",
 *     label = @Translation("Zipcode finder"),
 *     description = @Translation("A computed field to link a zipcode finder"),
 *     default_widget = "entity_reference_autocomplete",
 *     default_formatter = "entity_reference_label",
 *     list_class = "Drupal\zipcode_finder\Plugin\Field\FieldType\ZipcodeFinderComputedItemList",
 *     no_ui = true
 * )
 *
 */
class ZipcodeFinderComputedItem extends EntityReferenceItem
{

    /**
     * Whether or not the value has been calculated.
     *
     * @var bool
     */
    protected $isCalculated = FALSE;

    public static function defaultFieldSettings()
    {
        return [
                'target_type' => 'zipcode_finder',
            ] + parent::defaultStorageSettings();
    }

    /**
     * {@inheritdoc}
     */
    public function __get($name) {
        $this->ensureCalculated();
        return parent::__get($name);
    }

    public function get($property_name)
    {
        $this->ensureCalculated();
        return parent::get($property_name); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function isEmpty() {
        $this->ensureCalculated();
        return parent::isEmpty();
    }

    /**
     * {@inheritdoc}
     */
    public function getValue() {
        $this->ensureCalculated();
        return parent::getValue();
    }

    /**
     * Calculates the value of the field and sets it.
     */
    protected function ensureCalculated() {
        if (!$this->isCalculated) {
            $entity = $this->getEntity();
            if (!$entity->isNew()) {
                $zipcode = $entity->zipcode->value;
                if(empty($zipcode)) {
                    return null;
                }

                $finder = ZipcodeFinder::findByZipcode($zipcode);
                if($finder instanceof ZipcodeFinder) {
                    $this->isCalculated = TRUE;
                    $value = [
                        'target_id' => $finder->id(),
                    ];
                    $this->setValue($finder);
                }
            }

        }
    }

}
