<?php


namespace Drupal\relative_date_widget;

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\DateTimeComputed as BaseDateTimeComputed;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItem;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;

class DateTimeComputed extends BaseDateTimeComputed
{

    public function getValue()
    {
        if ($this->date !== NULL) {
            return $this->date;
        }

        /** @var \Drupal\Core\Field\FieldItemInterface $item */
        $item = $this->getParent();
        $value = $item->{($this->definition->getSetting('date source'))};

        $datetime_type = $item->getFieldDefinition()->getSetting('datetime_type');
        $storage_timezone = new \DateTimezone(DateTimeItemInterface::STORAGE_TIMEZONE);
        try {
            $date = new DrupalDateTime($value, $storage_timezone);
            if ($date instanceof DrupalDateTime && !$date->hasErrors()) {
                $this->date = $date;
                // If the format did not include an explicit time portion, then the
                // time will be set from the current time instead. For consistency, we
                // set the time to 12:00:00 UTC for date-only fields. This is used so
                // that the local date portion is the same, across nearly all time
                // zones.
                // @see \Drupal\Component\Datetime\DateTimePlus::setDefaultDateTime()
                // @see http://php.net/manual/datetime.createfromformat.php
                if ($datetime_type === DateTimeItem::DATETIME_TYPE_DATE) {
                    $this->date->setDefaultDateTime();
                }
            }
        }
        catch (\Exception $e) {
            // @todo Handle this.
        }

        return parent::getValue(); // TODO: Change the autogenerated stub
    }



}
