<?php

/**
 * @file
 * Contains sprowt_ckeditor_buttons.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sprowt_ckeditor_buttons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sprowt_ckeditor_buttons_entity_link module.
    case 'help.page.sprowt_ckeditor_buttons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This plugin adds buttons feature to the editor.') . '</p>';
      return $output;

    default:
  }
}
