<?php

namespace Drupal\sprowt_ai;

use Drupal\block\Entity\Block;
use Drupal\block_content\Entity\BlockContent;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseModalDialogCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Database\Connection;
use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\EntityFieldManager;
use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityWithPluginCollectionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormInterface;
use Drupal\Core\Form\FormValidator;
use Drupal\Core\Form\SubformState;
use Drupal\Core\Form\SubformStateInterface;
use Drupal\Core\Plugin\Context\Context;
use Drupal\Core\Plugin\Context\ContextDefinition;
use Drupal\Core\Plugin\Context\EntityContext;
use Drupal\Core\Render\Markup;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\TempStore\PrivateTempStore;
use Drupal\Core\Utility\Error;
use Drupal\Core\Utility\Token;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\FieldStorageConfigInterface;
use Drupal\inline_block_content\InlineBlockContentService;
use Drupal\inline_block_content\Plugin\Block\InlineBlock;
use Drupal\layout_builder\Form\ConfigureBlockFormBase;
use Drupal\layout_builder\Form\UpdateBlockForm;
use Drupal\layout_builder\LayoutTempstoreRepository;
use Drupal\layout_builder\Plugin\SectionStorage\OverridesSectionStorage;
use Drupal\layout_builder\Section;
use Drupal\layout_builder\SectionComponent;
use Drupal\layout_builder\SectionStorage\SectionStorageManager;
use Drupal\link\Plugin\Field\FieldType\LinkItem;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\sprowt_ai\Entity\AiSystem;
use Drupal\sprowt_ai\Form\RegenerateContentForm;
use Drupal\sprowt_ai\Plugin\Field\FieldType\PromptItem;
use Drupal\sprowt_ai\Plugin\Field\FieldWidget\PromptWidget;
use Drupal\sprowt_subsite\SettingsManager;
use Drupal\Tests\Core\Entity\RevisionableEntity;
use Drupal\text\Plugin\Field\FieldType\TextItemBase;

class AiService
{

    protected Connection $database;

    public static $statePrefix = 'sprowt_ai.ai_service';

    public function __construct(
        Connection $database,
    ) {
        $this->database = $database;
    }

    public function isEnabled()
    {
        $claude3Service = \Drupal::service('sprowt_ai.claude_3');
        return $claude3Service->isEnabled();
    }

    public static function AiSystemOptions() {
        $systems = AiSystem::loadMultiple();
        $systemOpts = [];
        /** @var AiSystem $system */
        foreach($systems as $system) {
            if(!$system->isEnabled()) {
                continue;
            }
            $label = $system->label();
            if(in_array($label, array_values($systemOpts))) {
                $key = array_search($system->label(), $systemOpts);
                $systemOpts[$key] = $system->label() . " [{$key}])";
                $label .= " [{$system->id()}]";
            }
            $systemOpts[$system->id()] = $label;
        }
        return $systemOpts;
    }

    public function fieldConfigFormAlter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
        if(!static::accountCanUseAi()) {
            return;
        }

        /** @var \Drupal\field\FieldConfigInterface $fieldConfig */
        $fieldConfig = $form_state->getFormObject()->getEntity();
        $type = $fieldConfig->getType();
        $entityType = $fieldConfig->getTargetEntityTypeId();
        $entityTypeDefinition = \Drupal::entityTypeManager()->getDefinition($entityType);
        $supportedTypes = \Drupal::config('sprowt_ai.settings')->get('supported_field_types');
        if(!in_array($type, $supportedTypes)) {
            return;
        }

        if(!is_a($entityTypeDefinition->getClass(), ContentEntityBase::class , true)) {
            return;
        }

        $settingsDefaults = $fieldConfig->getThirdPartySettings('sprowt_ai') ?? [];

        $settings = [
            '#type' => 'fieldset',
            '#title' => 'Sprowt AI settings',
            '#description' => 'Allow content for this field to be generated by Sprowt AI',
        ];

        $settings['enabled'] = [
            '#type' => 'checkbox',
            '#title' => 'Enable content generation',
            '#default_value' => $settingsDefaults['enabled'] ?? false,
            '#attributes' => [
                'class' => ['sprowt-ai-enabled'],
            ]
        ];

        $details = [
            '#type' => 'details',
            '#open' => true,
            '#title' => 'Details',
            '#states' => [
                'visible' => [
                    '.sprowt-ai-enabled' => ['checked' => true],
                ]
            ]
        ];

        if($type == 'link') {
            $details['subfields'] = [
                '#type' => 'checkboxes',
                '#title' => t('Enable for the following sub-fields:'),
                '#options' => [
                    'title' => 'Link text',
                    'aria_label' => 'Link description'
                ],
                '#default_value' => $settingsDefaults['subfields'] ?? [],
                '#states' => [
                    'required' => [
                        '.sprowt-ai-enabled' => ['checked' => true],
                    ]
                ]
            ];
        }

        $details['description'] = [
            '#type' => 'textarea',
            '#title' => 'Prompt field description',
            '#default_value' => $settingsDefaults['description'] ?? 'For help crafting a good prompt, see this <a href="https://docs.anthropic.com/en/docs/prompt-engineering" target="_blank">documentation</a>.',
        ];

        $details['max_tokens'] = [
            '#type' => 'number',
            '#title' => t('Max tokens'),
            '#default_value' => $settingsDefaults['max_tokens'] ?? 1024,
            '#description' => 'The maximum number of tokens to be consumed by the api.'
                . ' Tokens represent a sequence of characters.'
                . ' The max number defined here determines the size of the generated content.'
                . ' For more info see <a href="https://lunary.ai/anthropic-tokenizer" target="_blank">here</a>.',
            '#min' => 4,
            '#max' => 4096,
            '#step' => 1,
            '#required' => true
        ];


        $details['temperature'] = [
            '#type' => 'number',
            '#title' => t('Temperature'),
            '#default_value' => $settingsDefaults['temperature'] ?? 1.0,
            '#description' => 'Amount of randomness injected into the response.'
                . ' Ranges from 0.0 to 1.0.'
                . ' Use temperature closer to 0.0 for analytical / multiple choice, and closer to 1.0 for creative and generative tasks.'
                . ' Note that even with temperature of 0.0, the results will not be fully deterministic.',
            '#min' => 0,
            '#max' => 1,
            '#step' => 0.1,
            '#required' => true
        ];

        $settings['details'] = $details;


        $form['third_party_settings']['sprowt_ai'] = $settings;
        $form['#validate'][] = [static::class, 'alteredWidgetConfigValidate'];
    }

    public static function alteredWidgetConfigValidate(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
    {
        $sprowtAiSettings = $form_state->getValue(['third_party_settings', 'sprowt_ai']);
        $sprowtAiSettings['enabled'] = !empty($sprowtAiSettings['enabled']);
        $details = $sprowtAiSettings['details'] ?? [];
        if(isset($sprowtAiSettings['details'])) {
            unset($sprowtAiSettings['details']);
        }
        if(isset($details['subfields'])) {
            $details['subfields'] = array_filter(array_values($details['subfields']));
        }
        $sprowtAiSettings = array_merge($sprowtAiSettings, $details);
        $form_state->setValue(['third_party_settings', 'sprowt_ai'], $sprowtAiSettings);
    }

    public function widgetFormAlter(&$field_widget_complete_form, \Drupal\Core\Form\FormStateInterface $form_state, &$context)
    {
        if(!static::accountCanUseAi()) {
            return;
        }

        /** @var \Drupal\Core\Field\FieldItemListInterface $items */
        $items = $context['items'];
        $definition = $items->getFieldDefinition();
        $type = $definition->getType();
        $supportedTypes = \Drupal::config('sprowt_ai.settings')->get('supported_field_types');
        if(!in_array($type, $supportedTypes) || !($definition instanceof \Drupal\Core\Field\FieldConfigInterface)) {
            return;
        }

        /** @var ContentEntityBase $entity */
        $entity = $items->getEntity();

        $name = $definition->getName();
        $entityType = $definition->getTargetEntityTypeId();

        $form = &$context['form'];

        $formParents = isset($form['#array_parents']) ? $form['#array_parents'] : [];
        $formParents[] = $name;

        $fieldId = implode('--', [
            $definition->getTargetEntityTypeId(),
            $definition->getName()
        ]);

        $fieldKey = implode('__', [
            $definition->getTargetEntityTypeId(),
            $definition->getName()
        ]);

        $settings = $definition->getThirdPartySettings('sprowt_ai');
        if(empty($settings['enabled'])) {
            return;
        }

        $mainPropertyName = $definition->getFieldStorageDefinition()->getMainPropertyName();

        $subfields = [
            $mainPropertyName
        ];
        if(!empty($settings['subfields'])) {
            $subfields = $settings['subfields'];
        }

        foreach ($items as $delta => $item) {
            $parents = ['widget', $delta];
            $widgetKey = $fieldKey . '__' . $delta;
            $dataKey = $widgetKey;
            if(!$entity->isNew()) {
                $dataKey = $widgetKey . '__' . $entity->id();
            }
            foreach($subfields as $subfield) {
                $dataKey  .= '__' . $subfield;
                $widgetValueParents = array_merge($parents, [$subfield]);
                $widgetValueElement = NestedArray::getValue($field_widget_complete_form, $widgetValueParents);
                if(empty($widgetValueElement) || empty($widgetValueElement['#type'])) {
                    $widgetValueParents = $parents;
                    $widgetValueElement = NestedArray::getValue($field_widget_complete_form, $widgetValueParents);
                }
                if(empty($widgetValueElement)) {
                    continue;
                }
                $fieldElementId = $fieldId . '--' . $delta . '--' . $subfield;

                $selector = '[data-prompt-selector="' . trim($fieldElementId) . '"]';
                $widgetValueElement['#attributes']['data-prompt-selector'] = $fieldElementId;
                $text = 'Enable AI';
                $prompt = $this->getWidgetPrompt($entity, $name, $delta, $subfield);
                if(!empty($prompt)) {
                    $text = 'Generate content';
                }

                $options = [];
                $options['temperature'] = $settings['details']['temperature'] ?? 1.0;
                $options['tokenData'] = [
                    $entityType => $entity->id()
                ];

            $options['references'] = static::extractReferencesFromEntity($entity);
            $options['preprompt'] = static::getPrepromptText($entity);

                $routeMatch = \Drupal::routeMatch();
                $routeEntityType = $routeMatch->getParameter('entityType') ?? null;
                $routeEntityId = $routeMatch->getParameter('entityId') ?? null;
                if(!empty($routeEntityId) && !empty($routeEntityType) && !isset($options['tokenData'][$routeEntityType])) {
                    $options['tokenData'][$routeEntityType] = $routeEntityId;
                }
                $routeNode = $routeMatch->getParameter('node') ?? null;
                if(!empty($routeNode) && !isset($options['tokenData']['node'])) {
                    if($routeNode instanceof NodeInterface) {
                        $options['tokenData']['node'] = $routeNode->id();
                    }
                    else {
                        $options['tokenData']['node'] = $routeNode;
                    }
                }

                $routeName = $routeMatch->getRouteName();
                if($routeName == 'layout_builder.update_block') {
                    $sectionStorage = $routeMatch->getParameter('section_storage');
                    if(!empty($sectionStorage) && $sectionStorage instanceof OverridesSectionStorage) {
                        $layoutEntity = $sectionStorage->getContextValue('entity');
                        if(empty($options['tokenData'][$layoutEntity->getEntityTypeId()])) {
                            $options['tokenData'][$layoutEntity->getEntityTypeId()] = $layoutEntity->id();
                        }
                    }
                }

                $fieldPrefix = '<button type="button" class="sprowt-ai-generate-content-button button button--small" ' .
                    'data-widget-key="' . $dataKey . '" ' .
                    'data-selector="'.Html::escape($selector).'" ' .
                    'data-options="' . Html::escape(json_encode($options)).'" ' .
                    'data-entity-uuid="' . Html::escape($entity->uuid()) . '" ' .
                    'data-entity-bundle="' . Html::escape($entity->bundle()) . '" ' .
                    'data-entity-type="' . Html::escape($entity->getEntityTypeId()) . '" ' .
                    'data-widget-value-element="' . Html::escape(json_encode($widgetValueElement)) . '" ' .
                    'data-widget-value="'  . Html::escape($widgetValueElement['#default_value']) . '" ' .
                    'data-field-property="' .  Html::escape($subfield) . '" ' .
                    '>'.$text.'</button>';
                if(isset($widgetValueElement['#field_prefix'])) {
                    if(is_array($widgetValueElement['#field_prefix'])) {
                        $widgetValueElement['#field_prefix']['prompt_show'] = [
                            '#type' => 'markup',
                            '#markup' => Markup::create($fieldPrefix)
                        ];
                    }
                    else {
                        $widgetValueElement['#field_prefix'] = Markup::create($widgetValueElement['#field_prefix'] . $fieldPrefix);
                    }
                }
                else {
                    $widgetValueElement['#field_prefix'] = Markup::create($fieldPrefix);
                }
                $referenceId = $dataKey . '__reference_button';
                $referenceButton = [
                    '#type' => 'button',
                    '#value' => 'Insert reference -- ' . $referenceId,
                    '#ajax' => [
                        'callback' => [static::class, 'updateEntityReferencesAjax'],
                        'event' => 'click',
                        'progress' => [
                            'type' => 'throbber',
                            'message' => 'Please wait...',
                        ],
                    ],
                    '#name' => $referenceId,
                    '#attributes' => [
                        'class' => ['button', 'reference-button'],
                        'data-selector' => $selector,
                        'data-reference-button' => $dataKey,
                    ],
                    '#prefix' => '<div class="sprowt-ai-reference-button-wrapper hidden" data-key="' . $dataKey . '">',
                    '#suffix' => '</div>',
                    '#validate' => []
                ];

                NestedArray::setValue($field_widget_complete_form, $widgetValueParents, $widgetValueElement);

                $widgetForm = NestedArray::getValue($field_widget_complete_form, $parents);
                $widgetForm[$referenceId] = $referenceButton;
                $systemVal = $this->getWidgetSystem($entity, $name, $delta, $subfield);

                $detailParents = array_merge($formParents, $parents, [
                    $dataKey . '__prompt_details',
                ]);

                $promptParents = array_merge($detailParents, [
                    $dataKey . '__prompt'
                ]);
                $systemParents = array_merge($detailParents, [
                    $dataKey . '__system'
                ]);

                $promptAttrs = $form_state->get('sprowt_ai_prompt_fields') ?? [];

                $details = [
                    '#type' => 'container',
                    '#attributes' => [
                        'class' => ['sprowt-ai-details', 'hidden'],
                    ]
                ];


                $details[$dataKey . '__system'] = [
                    '#type' => 'hidden',
                    '#attributes' => [
                        'class' => ['system-field'],
                        'data-system-field' => $dataKey,
                    ]
                ];
                $details[$dataKey . '__prompt'] = [
                    '#type' => 'hidden',
                    '#attributes' => [
                        'class' => ['prompt-field'],
                        'data-prompt-field' => $dataKey,
                    ]
                ];

                $fieldAttrs = [
                    'formParents' => $promptParents,
                    'detailFormParents' => $detailParents,
                    'systemParents' => $systemParents,
                    'fieldName' => $name,
                    'delta' => $delta,
                    'entity_type' => $entityType,
                    'isNew' => $entity->isNew(),
                    'entity_id' => $entity->id(),
                    'entity_uuid' => $entity->uuid(),
                    'default_value' => $this->getWidgetPrompt($entity, $name, $delta, $subfield),
                    'default_system' => $systemVal,
                    'field_property' => $subfield,
                ];

                if (!empty($fieldAttrs['default_value'])) {
                    $details[$dataKey . '__prompt']['#default_value'] = $fieldAttrs['default_value'];
                }
                if (!empty($fieldAttrs['default_system'])) {
                    $details[$dataKey . '__system']['#default_value'] = $fieldAttrs['default_system'];
                }

                $promptAttrs[$dataKey] = $fieldAttrs;
                $form_state->set('sprowt_ai_prompt_fields', $promptAttrs);

                $widgetForm[$dataKey . '__prompt_details'] = $details;
                NestedArray::setValue($field_widget_complete_form, $parents, $widgetForm);
            }
        }
        $field_widget_complete_form['#attached']['library'][] = 'sprowt_ai/altered_widget';
    }

    public static function getPrepromptText(ContentEntityBase $entity, $options = []) {
        if(!$entity->hasField('field_pre_prompt')
            || $entity->get('field_pre_prompt')->isEmpty()
        ) {
            /** @var BlockContent $entity */
            if($entity->getEntityTypeId() == 'block_content'
                && !$entity->isReusable()
            )
            {
                /** @var InlineBlockContentService $inlineBlockService */
                $inlineBlockService = \Drupal::service('inline_block_content.manager');
                $hostEntity = $inlineBlockService->getEntityFromInlineBlockContent($entity);
                if($hostEntity instanceof ContentEntityBase) {
                    return static::getPrepromptText($hostEntity);
                }
            }
            return '';
        }

        $entityType = $entity->getEntityTypeId();
        /** @var PromptItem $promptItem */
        $promptItem = $entity->get('field_pre_prompt')->first();
        $promptText = $promptItem->value ?? '';
        if(is_array($promptText)) {
            $promptText = $promptText["promptValueWrapper"]["textarea"] ?? '';
        }
        $options['tokenData'] = [
            $entityType => $entity->id()
        ];

        $options['references'] = static::extractReferencesFromEntity($entity);
        $promptText = static::preparePrompt($promptText, $options);
        return $promptText;
    }

    public static function getUpdatedEntityFromForm(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
    {
        $formObj = $form_state->getFormObject();
        if ($formObj instanceof \Drupal\Core\Entity\EntityForm) {
            $entity = $formObj->getEntity();
            $form_display = EntityFormDisplay::collectRenderDisplay($entity, 'edit');
            $formStateCopy = clone $form_state;
            $formStateCopy->cleanValues();
            $form_display->extractFormValues($entity, $form, $formStateCopy);
            $values = $formStateCopy->getValues();
            foreach ($values as $key => $value) {
                if ($entity->hasField($key)) {
                    $entity->set($key, $value);
                }
            }
            return $entity;
        }
        elseif ($formObj instanceof ConfigureBlockFormBase) {
            $ref = new \ReflectionClass(get_class($formObj));
            $blockProp = $ref->getProperty('block');
            $blockProp->setAccessible(true);
            $block = $blockProp->getValue($formObj);
            $blockFormMethod = $ref->getMethod('getPluginForm');
            $blockFormMethod->setAccessible(true);
            $blockFormObj = $blockFormMethod->invoke($formObj, $block);

            if ($blockFormObj instanceof InlineBlock) {
                $block_form = NestedArray::getValue($form, $form_state->getTemporaryValue('block_form_parents'));
                /** @var \Drupal\block_content\BlockContentInterface $block */
                $block = $block_form['#block'];
                $form_display = EntityFormDisplay::collectRenderDisplay($block, 'edit');
                $formStateCopy = clone $form_state;
                $formStateCopy->cleanValues();
                $form_display->extractFormValues($block, $block_form, $formStateCopy);

                $values = $formStateCopy->getValue(['settings', 'block_form']);
                foreach ($values as $key => $value) {
                    if ($block->hasField($key)) {
                        $block->set($key, $value);
                    }
                }

                return $block;
            }
        }
        return null;
    }

    public static function updateEntityReferencesAjax(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
    {
        try {
            $trigger = $form_state->getTriggeringElement();
            $selector = $trigger['#attributes']['data-selector'] ?? null;
            $response = new AjaxResponse();
            if (empty($selector)) {
                $response->addCommand(new InvokeCommand('body', 'trigger', [
                    'updateEntityReferencesError',
                    [
                        'No selector found for trigger'
                    ]
                ]));
            }
            $entity = static::getUpdatedEntityFromForm($form, $form_state);
            if (!empty($entity)) {
                $references = static::extractReferencesFromEntity($entity);
                $preprompt = static::getPrepromptText($entity);
                $response->addCommand(new InvokeCommand($selector, 'trigger', [
                    'updateEntityReferences',
                    [
                        $references,
                        $preprompt
                    ]
                ]));
            }
            else {
                $response->addCommand(new InvokeCommand($selector, 'trigger', [
                    'updateEntityReferencesError',
                    [
                        'References could not be found'
                    ]
                ]));
            }
        } catch (\Exception $e) {
            Error::logException(\Drupal::logger('sprowt_ai'), $e);
            $response = new AjaxResponse();
            $response->addCommand(new InvokeCommand('body', 'trigger', [
                'updateEntityReferencesError',
                [
                    $e->getMessage(),
                ]
            ]));
        }
        return $response;
    }

    public static function alteredWidgetEntityFormValidation(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
    {
        if($form["#form_id"] == 'field_config_edit_form') {
            return;
        }
        $triggeringElement = $form_state->getTriggeringElement();
        $skipTriggerValues = [
            'Generate content',
            'Attach entities hidden button',
            'Insert document(s) into prompt'
        ];
        if(in_array($triggeringElement["#value"], $skipTriggerValues)) {
            return;
        }
        if(!empty($triggeringElement['#attributes']['data-reference-button'])) {
            return;
        }
        $tmpPrompts = static::getFromTemporaryStorage('sprowt_ai_prompt_fields_alter') ?? [];
        $promptAttrs = $form_state->get('sprowt_ai_prompt_fields') ?? [];
        foreach ($promptAttrs as $idx => $promptAttr) {
            $tmpidx = implode('::', [
                $promptAttr['entity_type'],
                $promptAttr['entity_uuid'],
                $promptAttr["fieldName"],
                $promptAttr["delta"],
                $promptAttr['field_property']
            ]);
            $formEntry = NestedArray::getValue($form, $promptAttr['formParents']);
            $valueParents = $formEntry['#parents'] ?? [];
            $promptValue = $form_state->getValue($valueParents) ?? null;
            if(!isset($promptAttr['value']) && isset($promptValue) && is_string($promptValue)) {
                $promptAttr['value'] = $promptValue;
            }
            $systemEntry = NestedArray::getValue($form, $promptAttr['systemParents']);
            $systemValueParents = $systemEntry['#parents'] ?? [];
            $systemValue = $form_state->getValue($systemValueParents) ?? null;
            if(!isset($promptAttr['system_value']) && !empty($systemValue)) {
                $promptAttr['system_value'] = $systemValue;
            }

            $tmpPrompts[$tmpidx] = $promptAttr;
            $detailFormEntry = NestedArray::getValue($form, $promptAttr['detailFormParents']);
            if(!empty($detailFormEntry)) {
                $detailParents = $detailFormEntry['#parents'];
                $form_state->unsetValue($detailParents);
            }
        }
        static::setToTemporaryStorage('sprowt_ai_prompt_fields_alter', $tmpPrompts);
    }

    public static function extractReferencesFromEntity(ContentEntityBase $entity)
    {
        $references = [];
        $entityType = $entity->getEntityTypeId();
        $entityTypeLabel = $entity->getEntityType()->getLabel();
        $entityBundle = $entity->bundle();
        $fieldDefinitions = $entity->getFieldDefinitions();
        foreach ($fieldDefinitions as $fieldDefinition) {
            $storage = $fieldDefinition->getFieldStorageDefinition();
            $fieldName = $fieldDefinition->getName();
            $field = $entity->get($fieldName);
            try {
                $fieldValue = sprowt_get_field_value($entity, $fieldName);
            }
            catch (\Exception $e) {
                Error::logException(\Drupal::logger('sprowt_ai'), $e);
                $fieldValue = null;
            }
            $referenceTitle = $fieldDefinition->getLabel();
            if(empty($referenceTitle)) {
                continue;
            }
            if ($field instanceof FieldItemListInterface) {
                if($storage->getCardinality() === 1) {
                    $referenceKey = implode('.', [
                        $entityType,
                        $entityBundle,
                        $fieldName,
                    ]);
                    $references[$referenceKey] = [
                        'label' => $entityTypeLabel . ' Field: ' . $referenceTitle,
                        'value' => $fieldValue ?? null,
                    ];
                }
                else {
                    $fieldValue = $fieldValue ?? [];
                    foreach ($field as $delta => $item) {
                        $referenceKey = implode('.', [
                            $entityType,
                            $entityBundle,
                            $fieldName,
                            $delta
                        ]);
                        $references[$referenceKey] = [
                            'label' => $entityTypeLabel . ' Field (delta:['.$delta.']): ' . $referenceTitle,
                            'value' => $fieldValue[$delta] ?? null,
                        ];
                    }
                }
            }
        }
        return $references;
    }

    public static function saveWidgetPrompt(ContentEntityBase $entity, $fieldName, $delta, $property, $prompt)
    {
        if(!empty($prompt) && !is_string($prompt)) {
            \Drupal::logger('sprowt_ai')->error('Prompt not a string for entity %type %id field %field delta %delta property %property', [
                '%type' => $entity->getEntityTypeId(),
                '%id' => $entity->id(),
                '%field' => $fieldName,
                '%delta' => $delta,
                '%property' => $property,
            ]);
            return;
        }

        if(!empty($prompt)) {
            $prompt = trim($prompt);
        }
        $row = [
            'entity_type' => $entity->getEntityTypeId(),
            'entity_id' => $entity->id(),
            'entity_uuid' => $entity->uuid(),
            'field_name' => $fieldName,
            'delta' => $delta,
            'prompt' => $prompt,
            'field_property' => $property,
        ];
        $idQparams = [
            ':entity_type' => $entity->getEntityTypeId(),
            ':entity_uuid' => $entity->uuid(),
            ':field_name' => $fieldName,
            ':delta' => $delta,
            ':field_property' => $property,
        ];
        $idQ = "
            SELECT id FROM {sprowt_ai_widget_prompts}
                      WHERE entity_type = :entity_type
                        AND entity_uuid = :entity_uuid
                        AND field_name = :field_name
                        AND delta = :delta
                        AND field_property = :field_property
        ";
        if($entity->getEntityType()->isRevisionable()) {
            $row['entity_revision_id'] = $entity->getRevisionId();
            if(isset($row['entity_revision_id'])) {
                $idQ .= " AND entity_revision_id = :entity_revision_id";
                $idQparams[':entity_revision_id'] = $entity->getRevisionId();
            }
            else {
                $idQ .= " AND entity_revision_id IS NULL";
            }
        }

        $database = \Drupal::database();

        $id = $database->query($idQ, $idQparams)->fetchField();
        if(!empty($id)) {
            if(empty($prompt)) {
                $database->delete('sprowt_ai_widget_prompts')
                    ->condition('id', $id)
                    ->execute();
            }
            else {
                $database->update('sprowt_ai_widget_prompts')
                    ->fields($row)
                    ->condition('id', $id)
                    ->execute();
            }
        }
        else {
            if(!empty($prompt)) {
                $database->insert('sprowt_ai_widget_prompts')
                    ->fields($row)
                    ->execute();
            }
        }
    }

    public static function saveWidgetSystem(ContentEntityBase $entity, $fieldName, $delta, $property, $system)
    {
        $row = [
            'entity_type' => $entity->getEntityTypeId(),
            'entity_id' => $entity->id(),
            'entity_uuid' => $entity->uuid(),
            'field_name' => $fieldName,
            'delta' => $delta,
            'system' => $system,
            'field_property' => $property,
        ];
        $idQparams = [
            ':entity_type' => $entity->getEntityTypeId(),
            ':entity_uuid' => $entity->uuid(),
            ':field_name' => $fieldName,
            ':delta' => $delta,
            ':field_property' => $property,
        ];
        $idQ = "
            SELECT id FROM {sprowt_ai_widget_prompts}
                      WHERE entity_type = :entity_type
                        AND entity_uuid = :entity_uuid
                        AND field_name = :field_name
                        AND delta = :delta
                        AND field_property = :field_property
        ";
        if($entity->getEntityType()->isRevisionable()) {
            $row['entity_revision_id'] = $entity->getRevisionId();
            if(isset($row['entity_revision_id'])) {
                $idQ .= " AND entity_revision_id = :entity_revision_id";
                $idQparams[':entity_revision_id'] = $entity->getRevisionId();
            }
            else {
                $idQ .= " AND entity_revision_id IS NULL";
            }
        }

        $database = \Drupal::database();

        $id = $database->query($idQ, $idQparams)->fetchField();
        if(!empty($id)) {
            if(empty($system)) {
                $database->update('sprowt_ai_widget_prompts')
                    ->fields([
                        'system' => null
                    ])
                    ->condition('id', $id)
                    ->execute();
            }
            else {
                $database->update('sprowt_ai_widget_prompts')
                    ->fields([
                        'system' => $system
                    ])
                    ->condition('id', $id)
                    ->execute();
            }
        }
    }

    public function getWidgetPrompt(ContentEntityBase $entity, $fieldName, $delta, $property)
    {

        $tmpPrompts = static::getFromTemporaryStorage('sprowt_ai_prompt_fields_alter') ?? [];
        $tmpidx = implode('::', [
            $entity->getEntityTypeId(),
            $entity->uuid(),
            $fieldName,
            $delta,
            $property
        ]);
        if (isset($tmpPrompts[$tmpidx])) {
            return $tmpPrompts[$tmpidx]['value'] ?? null;
        }

        $sql = "
            SELECT prompt FROM {sprowt_ai_widget_prompts}
                      WHERE entity_type = :entity_type
                        AND entity_uuid = :entity_uuid
                        AND field_name = :field_name
                        AND delta = :delta
                        AND field_property = :field_property
        ";
        $params = [
            ':entity_type' => $entity->getEntityTypeId(),
            ':entity_uuid' => $entity->uuid(),
            ':field_name' => $fieldName,
            ':delta' => $delta,
            ':field_property' => $property,
        ];
        if($entity->getEntityType()->isRevisionable()) {
            $rvid = $entity->getRevisionId();
            if(isset($rvid)) {
                $sql .= " AND entity_revision_id = :entity_revision_id";
                $params[':entity_revision_id'] = $rvid;
            }
            else {
                $sql .= " AND entity_revision_id IS NULL";
            }
        }
        $prompt = $this->database->query($sql, $params)->fetchField();
        if($prompt) {
            return $prompt;
        }
        return null;
    }

    public function getWidgetSystem(ContentEntityBase $entity, $fieldName, $delta, $property)
    {
        $tmpPrompts = static::getFromTemporaryStorage('sprowt_ai_prompt_fields_alter') ?? [];
        $tmpidx = implode('::', [
            $entity->getEntityTypeId(),
            $entity->uuid(),
            $fieldName,
            $delta,
            $property
        ]);
        if (isset($tmpPrompts[$tmpidx])) {
            return $tmpPrompts[$tmpidx]['system_value'] ?? null;
        }

        $sql = "
            SELECT system FROM {sprowt_ai_widget_prompts}
                      WHERE entity_type = :entity_type
                        AND entity_uuid = :entity_uuid
                        AND field_name = :field_name
                        AND delta = :delta
                        AND field_property = :field_property
        ";
        $params = [
            ':entity_type' => $entity->getEntityTypeId(),
            ':entity_uuid' => $entity->uuid(),
            ':field_name' => $fieldName,
            ':delta' => $delta,
            ':field_property' => $property,
        ];
        if($entity->getEntityType()->isRevisionable()) {
            $rvid = $entity->getRevisionId();
            if(isset($rvid)) {
                $sql .= " AND entity_revision_id = :entity_revision_id";
                $params[':entity_revision_id'] = $rvid;
            }
            else {
                $sql .= " AND entity_revision_id IS NULL";
            }
        }
        $system = $this->database->query($sql, $params)->fetchField();
        if(!empty($system)) {
            return $system;
        }
        return null;
    }

    public static function setToTemporaryStorage($key, $value)
    {
        /** @var PrivateTempStore $keyStore */
        $keyStore = \Drupal::service('tempstore.private')->get('sprowt_ai');
        $keyStore->set($key, $value);
    }

    public static function getFromTemporaryStorage($key) {
        /** @var PrivateTempStore $keyStore */
        $keyStore = \Drupal::service('tempstore.private')->get('sprowt_ai');
        return $keyStore->get($key);
    }

    public static function clearTemporaryStorage($key)
    {
        /** @var PrivateTempStore $keyStore */
        $keyStore = \Drupal::service('tempstore.private')->get('sprowt_ai');
        return $keyStore->delete($key);
    }

    public function postEntitySaveUpdate(EntityInterface $entity)
    {
        $prompts = static::getFromTemporaryStorage('sprowt_ai_prompt_fields_alter') ?? [];
        $update = false;
        foreach($prompts as $idx => $promptInfo) {
            if($entity->uuid() == $promptInfo['entity_uuid'] && $entity->getEntityTypeId() == $promptInfo['entity_type']) {
                $prompt = $promptInfo['value'] ?? null;
                $fieldName = $promptInfo['fieldName'];
                $delta = $promptInfo['delta'];
                $system = $promptInfo['system_value'] ?? null;
                $fieldProperty = $promptInfo['field_property'];
                if (!empty($prompt)) {
                    static::saveWidgetPrompt($entity, $fieldName, $delta, $fieldProperty, $prompt);
                    static::saveWidgetSystem($entity, $fieldName, $delta, $fieldProperty, $system);
                }
                else {
                    static::saveWidgetPrompt($entity, $fieldName, $delta, $fieldProperty, null);
                }
                unset($prompts[$idx]);
                $update = true;
            }
        }
        if(!empty($update)) {
            if(empty($prompts)) {
                static::clearTemporaryStorage('sprowt_ai_prompt_fields_alter');
            }
            else {
                static::setToTemporaryStorage('sprowt_ai_prompt_fields_alter', $prompts);
            }
        }
    }

    public function postEntityRevisionCreate(\Drupal\Core\Entity\EntityInterface $new_revision, \Drupal\Core\Entity\EntityInterface $entity)
    {

        /** @var AiService $service */
        $service = \Drupal::service('sprowt_ai.service');
        $service->postEntitySaveUpdate($new_revision);
        PromptWidget::postEntitySaveUpdate($new_revision);

        $fields = [];
        $sql = "
            SELECT * FROM {sprowt_ai_widget_prompts}
                      WHERE entity_type = :entity_type
                        AND entity_uuid = :entity_uuid
        ";
        $rows = \Drupal::database()
            ->query($sql,
                [
                    'entity_type' => $entity->getEntityTypeId(),
                    'entity_uuid' => $entity->uuid(),
                ]
            )->fetchAll(\PDO::FETCH_ASSOC);
        foreach ($rows as $row) {
            if(empty($fields[$row['field_name']])) {
                $fields[$row['field_name']] = [];
            }
            if(empty($fields[$row['field_name']][$row['delta']])) {
                $fields[$row['field_name']][$row['delta']] = [];
            }
            if(!in_array($row['field_property'], $fields[$row['field_name']][$row['delta']])) {
                $fields[$row['field_name']][$row['delta']][] = $row['field_property'];
            }
        }
        foreach($fields as $fieldName => $deltas) {
            foreach ($deltas as $delta => $fieldProperties) {
                foreach($fieldProperties as $fieldProperty) {
                    $prompt = static::getWidgetPrompt($entity, $fieldName, $delta, $fieldProperty);
                    $system = static::getWidgetSystem($entity, $fieldName, $delta, $fieldProperty);

                    $revisionPrompt = static::getWidgetPrompt($new_revision, $fieldName, $delta, $fieldProperty);
                    $revisionSystem = static::getWidgetSystem($new_revision, $fieldName, $delta, $fieldProperty);
                    if (empty($revisionPrompt) && !empty($prompt)) {
                        static::saveWidgetPrompt($new_revision, $fieldName, $delta, $fieldProperty, $prompt);
                    }
                    if (empty($revisionSystem) && !empty($system)) {
                        static::saveWidgetSystem($new_revision, $fieldName, $delta, $fieldProperty, $system);
                    }
                }
            }
        }
    }

    public function postEntityDelete(EntityInterface $entity, $revision = false)
    {
        $sql = "
            SELECT id FROM {sprowt_ai_widget_prompts}
                      WHERE entity_type = :entity_type
                        AND entity_uuid = :entity_uuid
        ";
        $params = [
            ':entity_type' => $entity->getEntityTypeId(),
            ':entity_uuid' => $entity->uuid(),
        ];
        if($entity->getEntityType()->isRevisionable() && $revision) {
            $sql .= " AND entity_revision_id = :entity_revision_id";
            $params[':entity_revision_id'] = $entity->getRevisionId();
        }
        $db = \Drupal::database();
        $ids = $db->query($sql, $params)->fetchCol();
        if(!empty($ids)) {
            $db->delete('sprowt_ai_widget_prompts')
                ->condition('id', $ids, 'IN')
                ->execute();
        }
    }

    public static function preparePrompt(string $promptText, array $options = [])
    {
        /** @var Claude3Service $service */
        $service = \Drupal::service('sprowt_ai.claude_3');
        return $service->preparePrompt($promptText, $options);
    }

    public function generateContent($promptText, $options = [])
    {
        try {
            /** @var Claude3Service $service */
            $service = \Drupal::service('sprowt_ai.claude_3');
            return $service->generateContentValue($promptText, $options);
        }
        catch (\Exception $e) {
            Error::logException(\Drupal::logger('sprowt_ai'), $e);
            $currentUser = \Drupal::currentUser();
            if ($currentUser->isAuthenticated()) {
                $context = [
                    'prompt' => $promptText,
                    'options' => $options,
                    'error' => $e->getMessage(),
                ];
                $errorText = t('An error occurred while generating content:<br><pre>@context</pre>', ['@context' => json_encode($context, JSON_PRETTY_PRINT)]);
                $errorMarkup = Markup::create($errorText);
                \Drupal::messenger()->addError($errorMarkup);
            }
            return [];
        }
    }

    public function generateContentWithPromptEntityField(&$entity, $promptFieldName, $options = [], $save = true, $newRevision = true)
    {
        /** @var ContentEntityBase $entity */
        $promptList = $entity->get($promptFieldName);
        if (empty($promptList)) {
            return false;
        }
        $fieldSettings = $entity->getFieldDefinition($promptFieldName)->getSettings();
        $insertField = $fieldSettings['insertField'] ?? null;
        if (empty($insertField)) {
            return false;
        }

        $inserts = $entity->get($insertField)->getValue();
        $updated = false;
        foreach ($promptList as $delta => $promptValue) {
            $promptText = $promptValue->value ?? null;
            if (empty($promptText)) {
                continue;
            }

            $insertFieldDef = $entity->getFieldDefinition($insertField);
            $storageDefinition = $insertFieldDef->getFieldStorageDefinition();
            $maxLength = $storageDefinition->getSetting('max_length') ?? 0;
            if ($maxLength > 0) {
                $options['charLimit'] = $maxLength;
            }


            $fieldType = $insertFieldDef->getType();
            $fieldTypeInstance  = \Drupal::service('plugin.manager.field.field_type')->createInstance($fieldType, [
                'field_definition' => $insertFieldDef,
                'name' => null, //have to set to something to avoid php warning
                'parent' => null //have to set to something to avoid php warning
            ]);
            $insertFieldSettings = $insertFieldDef->getSettings();

            if (empty($options['max_tokens'])) {
                $options['max_tokens'] = $fieldSettings['max_tokens'] ?? 1024;
            }
            if (empty($options['tokenData'])) {
                $options['tokenData'] = [];
            }

            $options['tokenData'][$entity->getEntityTypeId()] = $entity;

            if (empty($options['systemId'])) {
                $defaultSystem = sprowt_ai_default_system($entity);
                if(!empty($defaultSystem)) {
                    $options['systemId'] = $defaultSystem->id();
                }
            }

            $content = $this->generateContent($promptText, $options);
            if (!empty($content)) {
                $content = array_shift($content);
                $current = $inserts[$delta] ?? [];
                if(empty($current) && is_a($fieldTypeInstance, TextItemBase::class, true)) {
                    $current = [
                        'format' => 'full_html'
                    ];
                }
                $inserts[$delta] = array_merge($current, [
                    'value' => $content
                ]);
                $updated = true;
            }
        }
        if($updated) {
            $entity->set($insertField, $inserts);
            if($newRevision) {
                if(method_exists($entity, 'isRevisionable') && $entity->isRevisionable()) {
                    $entity->setNewRevision();
                }
            }
            if ($save) {
                $entity->save();
            }
        }

        return $updated;
    }

    /**
     * @param ContentEntityBase $entity
     * @param string $alteredFieldName
     * @param array $options
     * @param bool $save
     * @param bool $newRevision
     * @return bool
     */
    public function generateContentWithAlteredFieldWidget(&$entity, $alteredFieldName, $options = [], $save = true, $newRevision = true)
    {
        $updated = false;
        $fieldDefinition = $entity->getFieldDefinition($alteredFieldName);
        $storageDefinition = $fieldDefinition->getFieldStorageDefinition();
        $fieldType = $fieldDefinition->getType();
        $fieldTypeInstance  = \Drupal::service('plugin.manager.field.field_type')->createInstance($fieldType, [
            'field_definition' => $fieldDefinition,
            'name' => null, //have to set to something to avoid php warning
            'parent' => null //have to set to something to avoid php warning
        ]);
        $settings = $fieldDefinition->getThirdPartySettings('sprowt_ai') ?? [];
        if(empty($settings['enabled'])) {
            return false;
        }

        $mainPropertyName = $fieldDefinition->getFieldStorageDefinition()->getMainPropertyName();

        $subfields = [
            $mainPropertyName
        ];
        if(!empty($settings['subfields'])) {
            $subfields = $settings['subfields'];
        }

        $sql = "
                SELECT * FROM {sprowt_ai_widget_prompts}
                          WHERE entity_type = :entity_type
                            AND entity_uuid = :entity_uuid
                            AND field_name = :field_name
            ";
        $params = [
            'entity_type' => $entity->getEntityTypeId(),
            'entity_uuid' => $entity->uuid(),
            'field_name' => $alteredFieldName,
        ];
        if($entity->getEntityType()->isRevisionable()) {
            $sql .= " AND entity_revision_id = :entity_revision_id";
            $params[':entity_revision_id'] = $entity->getRevisionId();
        }

        $rows = \Drupal::database()->query($sql, $params)->fetchAll(\PDO::FETCH_ASSOC);

        if(empty($rows)) {
            return false;
        }

        $maxLength = $storageDefinition->getSetting('max_length') ?? 0;
        if ($maxLength > 0) {
            $options['charLimit'] = $maxLength;
        }

        if (empty($options['max_tokens'])) {
            $options['max_tokens'] = $settings['max_tokens'] ?? 1024;
        }
        if (empty($options['tokenData'])) {
            $options['tokenData'] = [];
        }

        $options['tokenData'][$entity->getEntityTypeId()] = $entity;

        if (empty($options['systemId'])) {
            $defaultSystem = sprowt_ai_default_system($entity);
            if(!empty($defaultSystem)) {
                $options['systemId'] = $defaultSystem->id();
            }
        }

        $currentValues = $entity->get($alteredFieldName)->getValue() ?? [];
        foreach($rows as $row) {
            $rowOptions = $options;
            $promptText = $row['prompt'] ?? null;
            if (empty($promptText)) {
                continue;
            }

            if(!empty($row['system'])) {
                $rowOptions['systemId'] = $row['system'];
            }

            $delta = $row['delta'];
            $property = $row['field_property'] ?? 'value';
            $schema = $storageDefinition->getSchema();
            $columns = $schema['columns'] ?? [];
            $propertyColumn = $columns[$property] ?? [];
            if(!empty($propertyColumn['length'])) {
                $rowOptions['charLimit'] = $propertyColumn['length'];
            }

            $content = $this->generateContent($promptText, $rowOptions);
            if (!empty($content)) {
                $content = array_shift($content);
                $current = $currentValues[$delta] ?? [];
                if(empty($current) && is_a($fieldTypeInstance, TextItemBase::class, true)) {
                    $current = [
                        'format' => 'full_html'
                    ];
                }
                if(empty($current) && is_a($fieldTypeInstance, LinkItem::class, true)) {
                    $current = [
                        'uri' => 'internal:/#'
                    ];
                }
                if($property == 'aria_label') {
                    $options = $current['options'] ?? [];
                    $attributes = $options['attributes'] ?? [];
                    $attributes['aria-label'] = $content;
                    $options['attributes'] = $attributes;
                    $currentValues[$delta] = array_merge($current, [
                        'options' => $options
                    ]);
                }
                else {
                    $currentValues[$delta] = array_merge($current, [
                        $property => $content
                    ]);
                }
                $updated = true;
            }
        }

        if($updated) {
            $entity->set($alteredFieldName, $currentValues);
            if($newRevision) {
                if(method_exists($entity, 'isRevisionable') && $entity->isRevisionable()) {
                    $entity->setNewRevision();
                }
            }
            if ($save) {
                $entity->save();
            }
        }

        return $updated;
    }

    public function entityHasPrompts($entity)
    {
        $sql = "
                SELECT field_name FROM {sprowt_ai_widget_prompts}
                          WHERE entity_type = :entity_type
                            AND entity_uuid = :entity_uuid
            ";

        $params = [
            'entity_type' => $entity->getEntityTypeId(),
            'entity_uuid' => $entity->uuid(),
        ];

        if($entity->getEntityType()->isRevisionable()) {
            $sql .= " AND entity_revision_id = :entity_revision_id";
            $params[':entity_revision_id'] = $entity->getRevisionId();
        }

        $fieldNames = \Drupal::database()->query($sql, $params)->fetchCol();
        $fieldNames = array_unique($fieldNames);

        if(method_exists($entity, 'getFieldDefinitions')) {
            $definitions = $entity->getFieldDefinitions();
            foreach ($definitions as $definition) {
                $fieldName = $definition->getName();
                if (in_array($fieldName, $fieldNames)) {
                    return true;
                }
                if ($definition instanceof FieldConfig) {
                    $type = $definition->getType();
                    if ($type == 'sprowt_ai_prompt') {
                        return true;
                    }
                }
            }
        }

        $return = false;
        if(method_exists($entity, 'hasField')) {
            $layoutBuilderField = OverridesSectionStorage::FIELD_NAME;
            /** @var InlineBlockContentService $inlineBlockService */
            $inlineBlockService = \Drupal::service('inline_block_content.manager');
            if ($entity->hasField($layoutBuilderField)) {
                /** @var \Drupal\layout_builder\Field\LayoutSectionItemList $sectionList */
                $sectionList = $entity->get($layoutBuilderField);
                $sections = $sectionList->getSections();
                /** @var Section $section */
                foreach ($sections as $section) {
                    $components = $section->getComponents();
                    foreach ($components as $component) {
                        $configuration = $component->get('configuration');
                        $pluginId = $configuration['id'];
                        if (strpos($pluginId, 'inline_block:') === 0) {
                            /** @var BlockContent $block */
                            $block = $inlineBlockService->loadInlineBlockFromComponent($component);
                            if (!empty($block)) {
                                $return |= $this->entityHasPrompts($block);
                            }
                        }
                    }
                }
            }
        }


        return $return;
    }

    public function extractPromptAttributesFromEntity($entity)
    {
        $definitions = $entity->getFieldDefinitions();
        $return = [];
        foreach($definitions as $definition) {
            $fieldName = $definition->getName();
            if($definition instanceof FieldConfig) {
                $type = $definition->getType();
                $fieldTypeInstance  = \Drupal::service('plugin.manager.field.field_type')->createInstance($type, [
                    'field_definition' => $definition,
                    'name' => null, //have to set to something to avoid php warning
                    'parent' => null //have to set to something to avoid php warning
                ]);
                $settings = $definition->getThirdPartySettings('sprowt_ai') ?? [];
                if(empty($settings['enabled'])) {
                    continue;
                }
                $sql = "
                SELECT * FROM {sprowt_ai_widget_prompts}
                          WHERE entity_type = :entity_type
                            AND entity_uuid = :entity_uuid
                            AND field_name = :field_name
            ";
                $params = [
                    'entity_type' => $entity->getEntityTypeId(),
                    'entity_uuid' => $entity->uuid(),
                    'field_name' => $fieldName,
                ];
                if($entity->getEntityType()->isRevisionable()) {
                    $sql .= " AND entity_revision_id = :entity_revision_id";
                    $params[':entity_revision_id'] = $entity->getRevisionId();
                }

                $rows = \Drupal::database()->query($sql, $params)->fetchAll(\PDO::FETCH_ASSOC);
                if(!empty($rows)) {
                    $return[$fieldName] = $rows;
                }
            }
        }
        return $return;
    }

    public function generateContentForEntity(&$entity, $save = true, $newRevision = true, $systemId = null)
    {
        $bundle = $entity->bundle();
        if($bundle == 'city_page_service_blurb') {
            $stop = true;
        }

        $definitions = $entity->getFieldDefinitions();
        $options = [];
        if (empty($options['tokenData'])) {
            $options['tokenData'] = [];
        }

        $options['references'] = static::extractReferencesFromEntity($entity);
        $options['preprompt'] = static::getPrepromptText($entity);

        if(empty($systemId)) {
            $defaultSystem = sprowt_ai_default_system($entity);
            if (!empty($defaultSystem)) {
                $options['systemId'] = $defaultSystem->id();
            }
        }
        else {
            $options['systemId'] = $systemId;
        }

        $options['tokenData'][$entity->getEntityTypeId()] = $entity;
        $updated = false;
        foreach($definitions as $definition) {
            $fieldName = $definition->getName();
            if($definition instanceof FieldConfig) {
                $type = $definition->getType();
                if($type == 'sprowt_ai_prompt') {
                    $updated |= $this->generateContentWithPromptEntityField($entity, $fieldName, $options, false, false);
                }
                else {
                    $updated |= $this->generateContentWithAlteredFieldWidget($entity, $fieldName, $options, false, false);
                }
            }
        }

        $defaultSystemId = sprowt_ai_default_system();
        if(!empty($defaultSystemId)) {
            $defaultSystemId = $defaultSystemId->id();
        }

        $layoutBuilderField = OverridesSectionStorage::FIELD_NAME;
        /** @var InlineBlockContentService $inlineBlockService */
        $inlineBlockService = \Drupal::service('inline_block_content.manager');
        if($entity->hasField($layoutBuilderField)) {
            $hideService = \Drupal::service('layout_builder_hide.service');
            /** @var \Drupal\layout_builder\Field\LayoutSectionItemList $sectionList */
            $sectionList = $entity->get($layoutBuilderField);
            $sections = $sectionList->getSections();
            $newSections = [];
            $sectionsUpdated = false;
            /** @var Section $section */
            foreach ($sections as $section) {
                $sectionConfig = $section->getLayout()->getConfiguration();
                if(!empty($sectionConfig['layout_builder_hide'])) {
                    $sectionArray = $section->toArray();
                    $newSections[] = Section::fromArray($sectionArray);
                    continue;
                }

                $components = $section->getComponents();
                $newComponentsArray = [];
                foreach($components as $component) {
                    $isHidden = $component->get('layout_builder_hide');
                    if(!empty($isHidden)) {
                        $newComponentsArray[] = $component->toArray();
                        continue;
                    }
                    $configuration = $component->get('configuration');
                    $pluginId = $configuration['id'];
                    if(strpos($pluginId, 'inline_block:') === 0) {
                        /** @var BlockContent $block */
                        $block = $inlineBlockService->loadInlineBlockFromComponent($component);
                        if(!empty($block)) {
                            $blockSystemId = null;
                            $blockSystem = sprowt_ai_default_system($block);
                            if (!empty($blockSystem) && !empty($blockSystem->id()) && $blockSystem->id() != $defaultSystemId) {
                                $blockSystemId = $blockSystem->id();
                            }
                            else {
                                $blockSystemId = $options['systemId'] ?? null;
                            }
                            $blockUpdated = $this->generateContentForEntity($block, true, true, $blockSystemId);
                            if ($blockUpdated) {
                                $configuration['block_revision_id'] = $block->getRevisionId();
                                $component->set('configuration', $configuration);
                                $sectionsUpdated = true;
                            }
                        }
                    }
                    $newComponentsArray[] = $component->toArray();
                }
                $sectionArray = $section->toArray();
                $sectionArray['components'] = $newComponentsArray;
                $newSections[] = Section::fromArray($sectionArray);
            }
            if($sectionsUpdated) {
                $entity->set($layoutBuilderField, $newSections);
                $updated = true;
            }
        }
        if($updated) {
            if ($newRevision) {
                $oldEntity = clone $entity;
                if ($entity->getEntityType()->isRevisionable()) {
                    $entity->setNewRevision();
                }
            }
            if ($save) {
                $entity->save();
                if($newRevision) {
                    static::postEntityRevisionCreate($entity, $oldEntity);
                }
                if($entity->hasField($layoutBuilderField)) {
                    //discard any temp changes in the layout
                    /** @var SectionStorageManager $sectionStorageManager */
                    $sectionStorageManager = \Drupal::service('plugin.manager.layout_builder.section_storage');
                    $sectionStorage = $sectionStorageManager->load('overrides',[
                        'entity' => EntityContext::fromEntity($entity),
                        'view_mode' => new Context(new ContextDefinition('string'), 'default'),
                    ]);
                    /** @var LayoutTempstoreRepository $tempStoreManager */
                    $tempStoreManager = \Drupal::service('layout_builder.tempstore_repository');
                    if($tempStoreManager->has($sectionStorage)) {
                        $tempStoreManager->delete($sectionStorage);
                    }
                }
            }
        }

        return $updated;
    }


    public function extractEntitiesFromPromptText($promptText)
    {
        $entities = [];
        /** @var Token $tokenService */
        $tokenService = \Drupal::service('token');
        $foundTokens = $tokenService->scan($promptText);
        $loadExample = function($idOrUUID) {
            if (preg_match('/^[\d]+$/', $idOrUUID)) {
                $example = \Drupal\sprowt_ai\Entity\SprowtAiExample::load($idOrUUID);
            }
            else {
                $example = \Drupal::entityTypeManager()->getStorage('sprowt_ai_example')->loadByProperties(['uuid' => $idOrUUID]);
                if (empty($example)) {
                    $example = null;
                }
                else {
                    $example = array_shift($example);
                }
            }
            return $example;
        };
        $loadContext = function ($idOrUUID) {
            if (preg_match('/^[\d]+$/', $idOrUUID)) {
                $context = \Drupal\sprowt_ai\Entity\Context::load($idOrUUID);
            }
            else {
                $context = \Drupal::entityTypeManager()->getStorage('sprowt_ai_context')->loadByProperties(['uuid' => $idOrUUID]);
                if (empty($context)) {
                    $context = null;
                }
                else {
                    $context = array_shift($context);
                }
            }
            return $context;
        };
        $loadMedia = function ($idOrUUID) {
            if (preg_match('/^[\d]+$/', $idOrUUID)) {
                $media = Drupal\media\Entity\Media::load($idOrUUID);
            }
            else {
                $media = \Drupal::entityTypeManager()->getStorage('media')->loadByProperties(['uuid' => $idOrUUID]);
                if (empty($media)) {
                    $media = null;
                }
                else {
                    $media = array_shift($media);
                }
            }
            return $media;
        };
        $addToArray = function ($entity) use (&$entities) {
            $entityType = $entity->getEntityTypeId();
            if (!isset($entities[$entityType])) {
                $entities[$entityType] = [];
            }
            $entities[$entityType][$entity->uuid()] = $entity;
        };
        foreach($foundTokens as $type => $tokens) {
            if($type == 'sprowt_ai') {
                foreach ($tokens as $tokenName => $token) {
                    $args = [];
                    if(strpos($tokenName, ':') !== false) {
                        $args = explode(':', $tokenName);
                        $tokenName = array_shift($args);
                    }
                    switch($tokenName) {
                        case 'example_prompt':
                        case 'example_result':
                            $example_id = $args[0] ?? null;
                            if(!empty($example_id)) {
                                $example = $loadExample($example_id);
                            }
                            if($example instanceof \Drupal\sprowt_ai\Entity\SprowtAiExample) {
                                $addToArray($example);
                            }
                            break;
                        case 'document_source':
                        case 'document_content':
                            $document_id = $args[0] ?? null;
                            $media = $loadMedia($document_id);
                            if ($media instanceof \Drupal\media\Entity\Media) {
                                $addToArray($media);
                            }
                            break;
                        case 'context':
                            $context_id = $args[0] ?? null;
                            if(!empty($context_id)) {
                                $context = $loadContext($context_id);
                                if ($context instanceof \Drupal\sprowt_ai\Entity\Context) {
                                    $addToArray($context);
                                }
                            }
                            break;
                        default:
                            $args = [
                                $promptText,
                                $entities
                            ];
                            $moreEntities = \Drupal::moduleHandler()->invokeAll('extract_entities_from_prompt', $args);
                            if(!empty($moreEntities)) {
                                $entities = NestedArray::mergeDeep($entities, $moreEntities);
                            }
                    }
                }
            }
        }
        return $entities;
    }

    public static function accountCanUseAi(AccountInterface $account = null) {
        if(!isset($account)) {
            $account = \Drupal::currentUser();
        }
        return $account->hasPermission('use sprowt_ai');
    }

    public static function regenerateContentFormAccess(AccountInterface $account)
    {
        $permission = static::accountCanUseAi($account);

        if ($permission && $account->isAuthenticated()) {
            $routeMatch = \Drupal::routeMatch();
            if($routeMatch->getRouteName() == 'contextual.render') {
                return AccessResult::allowed();
            }
            $entityType = $routeMatch->getParameter('entity_type');
            $entityId = $routeMatch->getParameter('entity_id');
            if(!empty($entityId) && !empty($entityType)) {
                $entity = RegenerateContentForm::loadEntity($entityType, $entityId);
                /** @var static $service */
                $service = \Drupal::service('sprowt_ai.service');
                if($service->isEnabled()) {
                    $access = $entity->access('update', $account);
                    $hasPrompts = $service->entityHasPrompts($entity);
                    return AccessResult::allowedIf(!empty($entity) && $access && $hasPrompts);
                }
            }
            else {
                $stop = true;
            }
        }

        return AccessResult::forbidden();
    }

    public static function accessAi(AccountInterface $account) {
        $permission = static::accountCanUseAi($account);
        if ($permission && $account->isAuthenticated()) {
            /** @var static $service */
            $service = \Drupal::service('sprowt_ai.service');
            return AccessResult::allowedIf($service->isEnabled());
        }
        return AccessResult::forbidden();
    }

}
