<?php

/**
 * @file
 * Primary module hooks for Layout Builder Hide module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;
use Drupal\layout_builder\Plugin\SectionStorage\OverridesSectionStorage;
use Drupal\layout_builder_hide\LayoutBuilderHideService;

/**
 * Implements hook_preprocess_HOOK().
 */
function layout_builder_hide_preprocess_layout(&$variables)
{

    $layout_settings = $variables["content"]["#settings"] ?? [];
    $hide = !empty($layout_settings["layout_builder_hide"]);
    $visibilitySettings = $layout_settings["layout_builder_hide__visibility"] ?? [];

    /** @var LayoutBuilderHideService $service */
    $service = \Drupal::service('layout_builder_hide.service');
    $isVisible = $service->isVisible($visibilitySettings);
    $hide |= empty($isVisible);

    $inPreview = !empty($variables["in_preview"]) || !empty($variables["content"]["#in_preview"]);
    if (empty($hide)) {
        return;
    }
    if ($inPreview) {
        $variables["attributes"]['data-hidden-section'] = 'true';
        $variables["content"]['#attributes'] = $variables['attributes'];
        $variables["content"]['#settings']['label'] .= ' [hidden]';
        $variables['#attached']['library'][] = 'layout_builder_hide/preview';
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function layout_builder_hide_theme_suggestions_layout_alter(array &$suggestions, array &$variables)
{
    $layout_settings = $variables["content"]["#settings"] ?? [];
    $hide = !empty($layout_settings["layout_builder_hide"]);

    $visibilitySettings = $layout_settings["layout_builder_hide__visibility"] ?? [];

    /** @var LayoutBuilderHideService $service */
    $service = \Drupal::service('layout_builder_hide.service');
    $isVisible = $service->isVisible($visibilitySettings);
    $hide |= empty($isVisible);


    $inPreview = !empty($variables["in_preview"]) || !empty($variables["content"]["#in_preview"]);
    if (empty($hide)) {
        return;
    }
    if ($inPreview) {
        return;
    }
    //hidden layouts should only use the layout_hide theme.
    $suggestions = ['layout_hide'];
}

/**
 * Implements hook_theme().
 */
function layout_builder_hide_theme($existing, $type, $theme, $path)
{
    return [
        'layout_hide' => []
    ];
}

/**
 * Implements hook_form_alter().
 */
function layout_builder_hide_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if(strpos($form_id, '_layout_builder_form') !== false) {
        $formObj = $form_state->getFormObject();
        if(!method_exists($formObj, 'getSectionStorage')) {
            return;
        }
        /** @var \Drupal\layout_builder\SectionStorageInterface $sectionStorage */
        $sectionStorage = $formObj->getSectionStorage();
        $form["actions"]['bulk_hide_components'] = [
            '#type' => 'link',
            '#title' => t('Bulk hide/show blocks'),
            '#weight' => 10,
            '#url' => Url::fromRoute('layout_builder_hide.bulk_hide_component_form',
                [
                    'section_storage_type' => $sectionStorage->getStorageType(),
                    'section_storage' => $sectionStorage->getStorageId(),
                ],
                [
                    'attributes' => [
                        'class' => [
                            'use-ajax',
                            'button',
                        ],
                        'data-dialog-type' => 'modal',
                        'data-dialog-options' => json_encode([
                            'width' => '85%',
                            'maxWidth' => '600px'
                        ])
                    ],
                ]
            ),
        ];
    }
}

function layout_builder_hide_element_info_alter(array &$elements)
{
    // Add a pre-render callback to the layout_builder element type.
    if (isset($elements['layout_builder'])) {
        $elements['layout_builder']['#pre_render'][] = [LayoutBuilderHideService::class, 'alterLayoutBuilderRender'];
    }
}
