<?php

/**
 * @file
 * Contains sprowt_ckeditor_columns.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sprowt_ckeditor_columns_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sprowt_ckeditor_columns':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This plugin adds columns feature to the editor.') . '</p>';
      return $output;

    default:
  }
}
