<?php

/**
 * @file
 * Functions for layout_builder_ids.
 */

/**
 * Implements template_preprocess_layout.
 */
function layout_builder_ids_preprocess_layout(&$variables) {
  $config = \Drupal::config('layout_builder_ids.settings');

  // If there is a layout builder id, set it in the attributes.
  if ($config->get('section_id') && isset($variables['content']['#settings']['layout_builder_id']) && $variables['content']['#settings']['layout_builder_id'] !== '') {

    // Set the id attribute.
    $variables['attributes']['id'] = $variables['content']['#settings']['layout_builder_id'];
  }
}
